FROM php:8.0-fpm-alpine

RUN apk update && apk add \
  curl \
  vim \
  jq \
  git

# Install composer to /usr/local/bin/composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Type docker-php-ext-install to see available extensions
RUN docker-php-ext-install pdo pdo_mysql calendar bcmath

WORKDIR /cloud-backend