<?php

namespace Container50SWPa0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicationFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PublicationFormType' shared autowired service.
     *
     * @return \App\Form\PublicationFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PublicationFormType.php';

        return $container->privates['App\\Form\\PublicationFormType'] = new \App\Form\PublicationFormType();
    }
}
