apiVersion: v1
kind: Service
metadata:
  name: cloud-backend-service-external
spec:
  selector:
    app: cloud-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer