<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUwHaKpU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUwHaKpU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUwHaKpU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUwHaKpU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUwHaKpU\App_KernelDevDebugContainer([
    'container.build_hash' => 'UwHaKpU',
    'container.build_id' => 'b3eaf75c',
    'container.build_time' => 1647465613,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUwHaKpU');
