<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMn3X1XL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMn3X1XL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMn3X1XL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMn3X1XL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMn3X1XL\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mn3X1XL',
    'container.build_id' => 'f070c580',
    'container.build_time' => 1647870102,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMn3X1XL');
