<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5hpVdQG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5hpVdQG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5hpVdQG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5hpVdQG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5hpVdQG\App_KernelDevDebugContainer([
    'container.build_hash' => '5hpVdQG',
    'container.build_id' => '965718bf',
    'container.build_time' => 1647591800,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5hpVdQG');
